spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  servlet:
    context-path: /message-rs

management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: health,logfile,loggers

logging:
  level:
    root: warn
    com.github.wensimin.messagers: debug
  file:
    name: log/log.log
